#!/bin/bash

read -p "Digite o primeiro número " num1
read -p "Digite o segundo número " num2

if ! [[ "num1" =~ ^[0-9]+$ ]]; then
  echo "nenhum número foi digitado"
  exit 1
fi

if ! [[ "num2" =~ ^[0-9]+$ ]]; then
  echo "nenum número foi digitado"
  exit 1
fi

soma=$(($num1+$num2))

echo "A soma é: "$soma
